server:
  port: 3030

spring:
  datasource:
    url: jdbc:mysql://localhost:8080/customer
    username: root
    password: root_Teste2024@
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate: 
      ddl-auto: update
    show-sql: true
  
  application:
    name: SPRING_PROJECT